services:
    contao_legacy.frontend_loader:
        class: Contao\Bundle\LegacyBundle\Routing\FrontendLoader
        arguments: ['@service_container']
        tags:
            - { name: routing.loader }